spring:
  application:
    name: config-server
  cloud:
    config:
      uri: http://localhost:8888  # Replace with your Config Server URL
      name: config-server  # The name of the application to fetch config for
      profile: dev # The profile to fetch config for
      import-check:
        enabled: false
      server:
        jdbc:
          sql: SELECT key, value FROM properties WHERE application=? AND profile=?
          order: 1
          datasource:
            driver-class-name: org.postgresql.Driver
            url: jdbc:postgresql://localhost:5432/mydatabase
            username: myuser
            password: secret
    flyway:
      enabled: true
      locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver